AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    {{ cookiecutter.project_name }}

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 5
        Runtime: python3.8
        Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
{%- if cookiecutter.include_safe_deployment == "y" %}
        AutoPublishAlias: live # More info about Safe Deployments: https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst
        DeploymentPreference:
            Type: Linear10PercentEvery1Minute {% endif %}
        Environment:
            Variables:
                # Powertools env vars: https://awslabs.github.io/aws-lambda-powertools-python/#environment-variables
                LOG_LEVEL: INFO
                POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
                POWERTOOLS_LOGGER_LOG_EVENT: true
                POWERTOOLS_METRICS_NAMESPACE: MyServerlessApplication
                POWERTOOLS_SERVICE_NAME: {{ cookiecutter.service_name }}

Resources:
    {{ cookiecutter.lambda_name|replace('_', ' ')|title()|replace(' ', '') }}Function:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            Handler: app.lambda_handler
            CodeUri: {{ cookiecutter.lambda_name }}
            Description: {{ cookiecutter.lambda_name|replace('_', ' ')|title() }} function
            Events:
                CatchAll:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /{{ cookiecutter.service_name }}
                        Method: GET
            # Policies: # Example inline policy
            #     - Version: "2012-10-17"
            #     Statement:
            #         - Effect: "Allow"
            #         Action:
            #             - "ssm:GetParameter"
            #         Resource:
            #             - "*"
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Tags:
                SOLUTION: MyServerlessApplication
                SOLUTION_MODULE: My{{ cookiecutter.lambda_name|replace('_', ' ')|title()|replace(' ', '') }}Function

    # Sample policy to add additional permissions to your Lambda
    {{ cookiecutter.lambda_name|replace('_', ' ')|title()|replace(' ', '') }}FunctionAdditionalPermission:
        Type: "AWS::IAM::Policy"
        Properties:
            PolicyName: "root"
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -
                        Effect: "Allow"
                        Action: "ssm:GetParameters"
                        Resource: "*"
            Roles:
                - !Ref {{ cookiecutter.lambda_name|replace('_', ' ')|title()|replace(' ', '') }}FunctionRole # Sample policy to demonstrate Implicit IAM Role created with SAM

Outputs:
    {{ cookiecutter.lambda_name|replace('_', ' ')|title()|replace(' ', '') }}ApigwURL:
      Description: "API Gateway endpoint URL for Prod environment for {{ cookiecutter.lambda_name|replace('_', ' ')|title() }} Function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/{{ cookiecutter.service_name }}"

    {{ cookiecutter.lambda_name|replace('_', ' ')|title()|replace(' ', '') }}Function:
      Description: "{{ cookiecutter.lambda_name|replace('_', ' ')|title() }} Lambda Function ARN"
      Value: !GetAtt {{ cookiecutter.lambda_name|replace('_', ' ')|title()|replace(' ', '') }}Function.Arn

